name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt update -m && sudo apt install libusb-1.0.0-dev libhidapi-dev gcovr cmake
        shell: bash
      - name: ghaction-cmake
        uses: lukka/run-cmake@master
        with:
          cmakeGenerator: UnixMakefiles
          buildDirectory: "${{ github.workspace }}/../../_temp"
      - name: Generate coverage
        run: cd "${{ github.workspace }}/../../_temp" && make coverage
