name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
        matrix:
          cc: [ gcc, clang ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: ghaction-cmake
        uses: docker://lpenz/ghaction-cmake:latest
        with:
          cc: ${{ matrix.cc }}
