name: C/C++ CI

on:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt update -m && sudo apt install libusb-1.0-0-dev libhidapi-dev gcovr cmake doxygen
        shell: bash
      - name: Run CMake
        run: cd "${{ github.workspace }}/../../_temp" && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug "${{ github.workspace }}"
      - name: Generate coverage
        run: cd "${{ github.workspace }}/../../_temp" && make coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: Code_Coverage_Report
          path: "${{ github.workspace }}/../../_temp/coverage"
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt update -m && sudo apt install libusb-1.0-0-dev libhidapi-dev gcovr cmake doxygen
        shell: bash
      - name: Run CMake
        run: cd "${{ github.workspace }}/../../_temp" && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug "${{ github.workspace }}"
      - name: Generate docs
        run: cd "${{ github.workspace }}/../../_temp" && make doxygen
      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: Doxygen_Docs
          path: "${{ github.workspace }}/../../_temp/html"
  publish-artifacts:
    runs-on: ubuntu-latest
    needs: [coverage, docs]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Move files
        run:
          rm -rf docs coverage
          mv Doxygen_Docs docs
          mv Code_Coverage_Report coverage
          find
        shell: bash

