name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
        matrix:
          cc: [ gcc, clang ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: ghaction-cmake
        uses: docker://lpenz/ghaction-cmake:latest
        with:
          cc: ${{ matrix.cc }}
          dependencies: libusb-1.0.0-dev libhidapi-dev
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: docker://lpenz/ghaction-cmake:latest
        with:
          coverage: codecov
          dependencies: libusb-1.0.0-dev libhidapi-dev
  valgrind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: docker://lpenz/ghaction-cmake:latest
        with:
          ctestflags: '-D ExperimentalMemCheck'
          dependencies: libusb-1.0.0-dev libhidapi-dev
  clang-sanitizers:
    name: build with clang -fsanitize
    strategy:
        matrix:
          cflags:
            - -fsanitize=address
            - -fsanitize=memory
            - -fsanitize=undefined
            - -fsanitize=dataflow
            - -fsanitize=safe-stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: docker://lpenz/ghaction-cmake:latest
        with:
          cc: clang
          cxx: clang
          cflags: ${{ matrix.cflags }}
          dependencies: libusb-1.0.0-dev libhidapi-dev
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://lpenz/ghaction-cmake:latest
        with:
          analyzer: clang-format
          dependencies: libusb-1.0.0-dev libhidapi-dev
  clang-analyzers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://lpenz/ghaction-cmake:latest
        with:
          analyzer: clang-tidy
          dependencies: libusb-1.0.0-dev libhidapi-dev
